spring.application.name=notification-queue-api
server.port=${SERVER_PORT:8080}

spring.datasource.url=jdbc:h2:mem:notifications
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.rabbitmq.listener.simple.auto-startup=${RABBIT_LISTENER_AUTO_STARTUP:false}
app.rabbitmq.exchange=notifications.exchange
app.rabbitmq.queue=notifications.queue
app.rabbitmq.routing-key=notifications.created

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
springdoc.swagger-ui.path=/docs
